# SPDX-License-Identifier: GPL-2.0

load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load(
    "//build/kernel/kleaf:kernel.bzl",
    "kernel_build",
)

_QCS8550_MODULES_LIST = [
    # keep sorted
    "crypto/michael_mic.ko",
    "drivers/base/regmap/regmap-sdw.ko",
    "drivers/bus/mhi/host/mhi.ko",
    "drivers/clk/qcom/camcc-sm8550.ko",
    "drivers/clk/qcom/clk-qcom.ko",
    "drivers/clk/qcom/clk-rpmh.ko",
    "drivers/clk/qcom/dispcc-sm8550.ko",
    "drivers/clk/qcom/gcc-sm8550.ko",
    "drivers/clk/qcom/gpucc-sm8550.ko",
    "drivers/clk/qcom/tcsrcc-sm8550.ko",
    "drivers/clk/qcom/videocc-sm8550.ko",
    "drivers/cpufreq/qcom-cpufreq-hw.ko",
    "drivers/crypto/qce/qcrypto.ko",
    "drivers/crypto/qcom-rng.ko",
    "drivers/dma/qcom/bam_dma.ko",
    "drivers/dma/qcom/gpi.ko",
    "drivers/dma-buf/heaps/system_heap.ko",
    "drivers/firmware/qcom/qcom-scm.ko",
    "drivers/firmware/qcom/qcom_tzmem.ko",
    "drivers/gpu/drm/bridge/aux-bridge.ko",
    "drivers/gpu/drm/bridge/aux-hpd-bridge.ko",
    "drivers/gpu/drm/bridge/display-connector.ko",
    "drivers/gpu/drm/bridge/lontium-lt8912b.ko",
    "drivers/gpu/drm/display/drm_display_helper.ko",
    "drivers/gpu/drm/display/drm_dp_aux_bus.ko",
    "drivers/gpu/drm/msm/msm.ko",
    "drivers/gpu/drm/scheduler/gpu-sched.ko",
    "drivers/gpu/drm/drm_exec.ko",
    "drivers/gpu/drm/drm_gpuvm.ko",
    "drivers/hwmon/hwmon.ko",
    "drivers/hwmon/pwm-fan.ko",
    "drivers/hwspinlock/qcom_hwspinlock.ko",
    "drivers/i2c/busses/i2c-qcom-cci.ko",
    "drivers/i2c/busses/i2c-qcom-geni.ko",
    "drivers/input/misc/pm8941-pwrkey.ko",
    "drivers/input/rmi4/rmi_core.ko",
    "drivers/input/rmi4/rmi_i2c.ko",
    "drivers/input/touchscreen/edt-ft5x06.ko",
    "drivers/input/touchscreen/hynitron_cstxxx.ko",
    "drivers/interconnect/qcom/icc-bcm-voter.ko",
    "drivers/interconnect/qcom/icc-osm-l3.ko",
    "drivers/interconnect/qcom/icc-rpmh.ko",
    "drivers/interconnect/qcom/qnoc-sm8550.ko",
    "drivers/interconnect/icc-clk.ko",
    "drivers/iommu/arm/arm-smmu/arm_smmu.ko",
    "drivers/irqchip/qcom-pdc.ko",
    "drivers/leds/flash/leds-qcom-flash.ko",
    "drivers/leds/rgb/leds-group-multicolor.ko",
    "drivers/leds/rgb/leds-pwm-multicolor.ko",
    "drivers/leds/rgb/leds-qcom-lpg.ko",
    "drivers/mailbox/qcom-ipcc.ko",
    "drivers/media/platform/qcom/camss/qcom-camss.ko",
    "drivers/media/platform/qcom/iris/qcom-iris.ko",
    "drivers/mfd/qcom-spmi-pmic.ko",
    "drivers/misc/fastrpc.ko",
    "drivers/mmc/host/cqhci.ko",
    "drivers/mmc/host/sdhci-msm.ko",
    "drivers/mux/mux-core.ko",
    "drivers/net/ipa/ipa.ko",
    "drivers/net/wireless/ath/ath12k/ath12k.ko",
    "drivers/nvmem/nvmem_qcom-spmi-sdam.ko",
    "drivers/nvmem/nvmem_qfprom.ko",
    "drivers/pci/pwrctrl/pci-pwrctrl-pwrseq.ko",
    "drivers/phy/qualcomm/phy-qcom-eusb2-repeater.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-combo.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-pcie.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-pcie-msm8996.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-ufs.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-usb.ko",
    "drivers/phy/qualcomm/phy-qcom-qmp-usbc.ko",
    "drivers/phy/phy-snps-eusb2.ko",
    "drivers/pinctrl/qcom/pinctrl-lpass-lpi.ko",
    "drivers/pinctrl/qcom/pinctrl-msm.ko",
    "drivers/pinctrl/qcom/pinctrl-sm8550.ko",
    "drivers/pinctrl/qcom/pinctrl-sm8550-lpass-lpi.ko",
    "drivers/pinctrl/qcom/pinctrl-spmi-gpio.ko",
    "drivers/pinctrl/qcom/pinctrl-spmi-mpp.ko",
    "drivers/pmdomain/qcom/rpmhpd.ko",
    "drivers/power/reset/nvmem-reboot-mode.ko",
    "drivers/power/reset/qcom-pon.ko",
    "drivers/power/reset/reboot-mode.ko",
    "drivers/power/sequencing/pwrseq-qcom-wcn.ko",
    "drivers/power/supply/qcom_battmgr.ko",
    "drivers/regulator/qcom-rpmh-regulator.ko",
    "drivers/remoteproc/qcom_common.ko",
    "drivers/remoteproc/qcom_pil_info.ko",
    "drivers/remoteproc/qcom_q6v5.ko",
    "drivers/remoteproc/qcom_q6v5_pas.ko",
    "drivers/remoteproc/qcom_sysmon.ko",
    "drivers/rpmsg/qcom_glink.ko",
    "drivers/rpmsg/qcom_glink_rpm.ko",
    "drivers/rpmsg/qcom_glink_smem.ko",
    "drivers/rpmsg/qcom_smd.ko",
    "drivers/rtc/rtc-pm8xxx.ko",
    "drivers/slimbus/slimbus.ko",
    "drivers/scsi/sg.ko",
    "drivers/soc/qcom/apr.ko",
    "drivers/soc/qcom/cmd-db.ko",
    "drivers/soc/qcom/icc-bwmon.ko",
    "drivers/soc/qcom/llcc-qcom.ko",
    "drivers/soc/qcom/mdt_loader.ko",
    "drivers/soc/qcom/pdr_interface.ko",
    "drivers/soc/qcom/pmic_glink.ko",
    "drivers/soc/qcom/pmic_glink_altmode.ko",
    "drivers/soc/qcom/qcom_aoss.ko",
    "drivers/soc/qcom/qcom_ice.ko",
    "drivers/soc/qcom/qcom_pd_mapper.ko",
    "drivers/soc/qcom/qcom_pdr_msg.ko",
    "drivers/soc/qcom/qcom_rpmh.ko",
    "drivers/soc/qcom/qcom_stats.ko",
    "drivers/soc/qcom/qmi_helpers.ko",
    "drivers/soc/qcom/rmtfs_mem.ko",
    "drivers/soc/qcom/smem.ko",
    "drivers/soc/qcom/smp2p.ko",
    "drivers/soc/qcom/socinfo.ko",
    "drivers/soc/qcom/ubwc_config.ko",
    "drivers/soundwire/soundwire-bus.ko",
    "drivers/soundwire/soundwire-qcom.ko",
    "drivers/spi/spi-geni-qcom.ko",
    "drivers/spmi/spmi-pmic-arb.ko",
    "drivers/tee/qcomtee/qcomtee.ko",
    "drivers/tee/tee.ko",
    "drivers/thermal/qcom/qcom-spmi-temp-alarm.ko",
    "drivers/thermal/qcom/qcom_tsens.ko",
    "drivers/ufs/host/ufs-qcom.ko",
    "drivers/usb/typec/mux/gpio-sbu-mux.ko",
    "drivers/usb/typec/ucsi/ucsi_glink.ko",
    "drivers/video/backlight/pwm_bl.ko",
    "net/mac80211/mac80211.ko",
    "net/qrtr/qrtr.ko",
    "net/qrtr/qrtr-mhi.ko",
    "net/qrtr/qrtr-smd.ko",
    "net/wireless/cfg80211.ko",
    "sound/soc/codecs/snd-soc-aw88166.ko",
    "sound/soc/codecs/snd-soc-aw88395-lib.ko",
    "sound/soc/codecs/snd-soc-hdmi-codec.ko",
    "sound/soc/codecs/snd-soc-lpass-macro-common.ko",
    "sound/soc/codecs/snd-soc-lpass-rx-macro.ko",
    "sound/soc/codecs/snd-soc-lpass-tx-macro.ko",
    "sound/soc/codecs/snd-soc-lpass-va-macro.ko",
    "sound/soc/codecs/snd-soc-lpass-wsa-macro.ko",
    "sound/soc/codecs/snd-soc-wcd-classh.ko",
    "sound/soc/codecs/snd-soc-wcd-common.ko",
    "sound/soc/codecs/snd-soc-wcd-mbhc.ko",
    "sound/soc/codecs/snd-soc-wcd938x.ko",
    "sound/soc/codecs/snd-soc-wcd938x-sdw.ko",
    "sound/soc/qcom/qdsp6/q6adm.ko",
    "sound/soc/qcom/qdsp6/q6afe.ko",
    "sound/soc/qcom/qdsp6/q6afe-clocks.ko",
    "sound/soc/qcom/qdsp6/q6afe-dai.ko",
    "sound/soc/qcom/qdsp6/q6apm-dai.ko",
    "sound/soc/qcom/qdsp6/q6apm-lpass-dais.ko",
    "sound/soc/qcom/qdsp6/q6asm.ko",
    "sound/soc/qcom/qdsp6/q6asm-dai.ko",
    "sound/soc/qcom/qdsp6/q6core.ko",
    "sound/soc/qcom/qdsp6/q6prm.ko",
    "sound/soc/qcom/qdsp6/q6prm-clocks.ko",
    "sound/soc/qcom/qdsp6/q6routing.ko",
    "sound/soc/qcom/qdsp6/snd-q6apm.ko",
    "sound/soc/qcom/qdsp6/snd-q6dsp-common.ko",
    "sound/soc/qcom/snd-soc-qcom-common.ko",
    "sound/soc/qcom/snd-soc-qcom-sdw.ko",
    "sound/soc/qcom/snd-soc-sc8280xp.ko",
]

kernel_build(
    name = "kernel_aarch64_qcs8550",
    srcs = ["//vendor/ayn/kernel:kernel_aarch64_sources",],
    outs = [],
    arch = "arm64",

    # Enable mixed build.
    base_kernel = "//vendor/ayn/kernel:kernel_aarch64",
    collect_unstripped_modules = True,
    defconfig = "//vendor/ayn/kernel:arch/arm64/configs/gki_defconfig",
    kmi_symbol_list = "//vendor/ayn/kernel:gki/aarch64/symbols/ayn",
    make_goals = [
        "modules",
    ],
    makefile = "//vendor/ayn/kernel:Makefile",
    module_outs = _QCS8550_MODULES_LIST,
    pre_defconfig_fragments = ["qcs8550.fragment"],
    strip_modules = True,
    visibility = ["//vendor/ayn:__subpackages__"],
)

pkg_files(
    name = "qcs8550_dist_files",
    srcs = [
        ":kernel_aarch64_qcs8550",
        # Mixed build: Additional GKI artifacts.
        "//vendor/ayn/kernel:kernel_aarch64",
        "//vendor/ayn/kernel:kernel_aarch64_modules",
        "//vendor/ayn/kernel:kernel_aarch64_system_dlkm_image",
    ],
    strip_prefix = strip_prefix.files_only(),
)
pkg_install(
    name = "qcs8550_dist",
    srcs = [":qcs8550_dist_files"],
    destdir = "out/ayn_qcs8550/dist",
)
